steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - 'beta'
  - 'run'
  - 'deploy'
  - 'default'
  - '--region'
  - 'europe-west2'
  - '--platform'
  - 'managed'
  - '--source'
  - 'app/'
